name: The Engagement
favicon: null
layout_spectrum: 0.24368
typography_spectrum: 0.8114451051224023
title: The Engagement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 1
  lightness: 1
  saturation: 0.9794108208734542
  rhythmicContrast: 0
purpose: []
